/*
 * aiproductdataenhancer/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using aiproductdataenhancer.Client;
using aiproductdataenhancer.Api;
// uncomment below to import models
//using aiproductdataenhancer.Model;

namespace aiproductdataenhancer.Test.Api
{
    /// <summary>
    ///  Class for testing AiProductDataEnhancerApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AiProductDataEnhancerApiTests : IDisposable
    {
        private AiProductDataEnhancerApi instance;

        public AiProductDataEnhancerApiTests()
        {
            instance = new AiProductDataEnhancerApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AiProductDataEnhancerApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' AiProductDataEnhancerApi
            //Assert.IsType<AiProductDataEnhancerApi>(instance);
        }

        /// <summary>
        /// Test AiProductDataEnhancerFillProductData
        /// </summary>
        [Fact]
        public void AiProductDataEnhancerFillProductDataTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //AiproductdataenhancerFillProductDataRequest body = null;
            //var response = instance.AiProductDataEnhancerFillProductData(body);
            //Assert.IsType<AiproductdataenhancerFillProductDataResponse>(response);
        }
    }
}
