/*
 * aiproductdataenhancer/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using aiproductdataenhancer.Model;
using aiproductdataenhancer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace aiproductdataenhancer.Test.Model
{
    /// <summary>
    ///  Class for testing AiproductdataenhancerTranslateDataResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AiproductdataenhancerTranslateDataResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AiproductdataenhancerTranslateDataResponse
        //private AiproductdataenhancerTranslateDataResponse instance;

        public AiproductdataenhancerTranslateDataResponseTests()
        {
            // TODO uncomment below to create an instance of AiproductdataenhancerTranslateDataResponse
            //instance = new AiproductdataenhancerTranslateDataResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AiproductdataenhancerTranslateDataResponse
        /// </summary>
        [Fact]
        public void AiproductdataenhancerTranslateDataResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" AiproductdataenhancerTranslateDataResponse
            //Assert.IsType<AiproductdataenhancerTranslateDataResponse>(instance);
        }

        /// <summary>
        /// Test the property 'DataTranslated'
        /// </summary>
        [Fact]
        public void DataTranslatedTest()
        {
            // TODO unit test for the property 'DataTranslated'
        }

        /// <summary>
        /// Test the property 'ConfidenceRate'
        /// </summary>
        [Fact]
        public void ConfidenceRateTest()
        {
            // TODO unit test for the property 'ConfidenceRate'
        }

        /// <summary>
        /// Test the property 'CompletionRate'
        /// </summary>
        [Fact]
        public void CompletionRateTest()
        {
            // TODO unit test for the property 'CompletionRate'
        }
    }
}
