/*
 * aiproductdataenhancer/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using aiproductdataenhancer.Model;
using aiproductdataenhancer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace aiproductdataenhancer.Test.Model
{
    /// <summary>
    ///  Class for testing AiproductdataenhancerFillProductDataCheckResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AiproductdataenhancerFillProductDataCheckResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AiproductdataenhancerFillProductDataCheckResponse
        //private AiproductdataenhancerFillProductDataCheckResponse instance;

        public AiproductdataenhancerFillProductDataCheckResponseTests()
        {
            // TODO uncomment below to create an instance of AiproductdataenhancerFillProductDataCheckResponse
            //instance = new AiproductdataenhancerFillProductDataCheckResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AiproductdataenhancerFillProductDataCheckResponse
        /// </summary>
        [Fact]
        public void AiproductdataenhancerFillProductDataCheckResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" AiproductdataenhancerFillProductDataCheckResponse
            //Assert.IsType<AiproductdataenhancerFillProductDataCheckResponse>(instance);
        }

        /// <summary>
        /// Test the property 'ProductDataFilled'
        /// </summary>
        [Fact]
        public void ProductDataFilledTest()
        {
            // TODO unit test for the property 'ProductDataFilled'
        }

        /// <summary>
        /// Test the property 'ConfidenceRate'
        /// </summary>
        [Fact]
        public void ConfidenceRateTest()
        {
            // TODO unit test for the property 'ConfidenceRate'
        }

        /// <summary>
        /// Test the property 'CompletionRate'
        /// </summary>
        [Fact]
        public void CompletionRateTest()
        {
            // TODO unit test for the property 'CompletionRate'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }
    }
}
