/*
 * aiproductdataenhancer/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using aiproductdataenhancer.Model;
using aiproductdataenhancer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace aiproductdataenhancer.Test.Model
{
    /// <summary>
    ///  Class for testing AiproductdataenhancerTranslateDataRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AiproductdataenhancerTranslateDataRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AiproductdataenhancerTranslateDataRequest
        //private AiproductdataenhancerTranslateDataRequest instance;

        public AiproductdataenhancerTranslateDataRequestTests()
        {
            // TODO uncomment below to create an instance of AiproductdataenhancerTranslateDataRequest
            //instance = new AiproductdataenhancerTranslateDataRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AiproductdataenhancerTranslateDataRequest
        /// </summary>
        [Fact]
        public void AiproductdataenhancerTranslateDataRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" AiproductdataenhancerTranslateDataRequest
            //Assert.IsType<AiproductdataenhancerTranslateDataRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'LanguageCode'
        /// </summary>
        [Fact]
        public void LanguageCodeTest()
        {
            // TODO unit test for the property 'LanguageCode'
        }

        /// <summary>
        /// Test the property 'DataToTranslate'
        /// </summary>
        [Fact]
        public void DataToTranslateTest()
        {
            // TODO unit test for the property 'DataToTranslate'
        }
    }
}
