/*
 * aiproductdataenhancer/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using aiproductdataenhancer.Model;
using aiproductdataenhancer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace aiproductdataenhancer.Test.Model
{
    /// <summary>
    ///  Class for testing AiproductdataenhancerFillProductDataRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AiproductdataenhancerFillProductDataRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AiproductdataenhancerFillProductDataRequest
        //private AiproductdataenhancerFillProductDataRequest instance;

        public AiproductdataenhancerFillProductDataRequestTests()
        {
            // TODO uncomment below to create an instance of AiproductdataenhancerFillProductDataRequest
            //instance = new AiproductdataenhancerFillProductDataRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AiproductdataenhancerFillProductDataRequest
        /// </summary>
        [Fact]
        public void AiproductdataenhancerFillProductDataRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" AiproductdataenhancerFillProductDataRequest
            //Assert.IsType<AiproductdataenhancerFillProductDataRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'LanguageCode'
        /// </summary>
        [Fact]
        public void LanguageCodeTest()
        {
            // TODO unit test for the property 'LanguageCode'
        }

        /// <summary>
        /// Test the property 'ProductInformation'
        /// </summary>
        [Fact]
        public void ProductInformationTest()
        {
            // TODO unit test for the property 'ProductInformation'
        }

        /// <summary>
        /// Test the property 'ProductDataToFill'
        /// </summary>
        [Fact]
        public void ProductDataToFillTest()
        {
            // TODO unit test for the property 'ProductDataToFill'
        }

        /// <summary>
        /// Test the property 'DomainsToInclude'
        /// </summary>
        [Fact]
        public void DomainsToIncludeTest()
        {
            // TODO unit test for the property 'DomainsToInclude'
        }

        /// <summary>
        /// Test the property 'DomainsToExclude'
        /// </summary>
        [Fact]
        public void DomainsToExcludeTest()
        {
            // TODO unit test for the property 'DomainsToExclude'
        }
    }
}
