/*
 * aiproductdataenhancer/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using aiproductdataenhancer.Model;
using aiproductdataenhancer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace aiproductdataenhancer.Test.Model
{
    /// <summary>
    ///  Class for testing AiproductdataenhancerJobStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AiproductdataenhancerJobStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AiproductdataenhancerJobStatus
        //private AiproductdataenhancerJobStatus instance;

        public AiproductdataenhancerJobStatusTests()
        {
            // TODO uncomment below to create an instance of AiproductdataenhancerJobStatus
            //instance = new AiproductdataenhancerJobStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AiproductdataenhancerJobStatus
        /// </summary>
        [Fact]
        public void AiproductdataenhancerJobStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" AiproductdataenhancerJobStatus
            //Assert.IsType<AiproductdataenhancerJobStatus>(instance);
        }
    }
}
