/*
 * aiproductdataenhancer/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using aiproductdataenhancer.Model;
using aiproductdataenhancer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace aiproductdataenhancer.Test.Model
{
    /// <summary>
    ///  Class for testing AiproductdataenhancerGenerateProductDataRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AiproductdataenhancerGenerateProductDataRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AiproductdataenhancerGenerateProductDataRequest
        //private AiproductdataenhancerGenerateProductDataRequest instance;

        public AiproductdataenhancerGenerateProductDataRequestTests()
        {
            // TODO uncomment below to create an instance of AiproductdataenhancerGenerateProductDataRequest
            //instance = new AiproductdataenhancerGenerateProductDataRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AiproductdataenhancerGenerateProductDataRequest
        /// </summary>
        [Fact]
        public void AiproductdataenhancerGenerateProductDataRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" AiproductdataenhancerGenerateProductDataRequest
            //Assert.IsType<AiproductdataenhancerGenerateProductDataRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'LanguageCode'
        /// </summary>
        [Fact]
        public void LanguageCodeTest()
        {
            // TODO unit test for the property 'LanguageCode'
        }

        /// <summary>
        /// Test the property 'ProductInformation'
        /// </summary>
        [Fact]
        public void ProductInformationTest()
        {
            // TODO unit test for the property 'ProductInformation'
        }

        /// <summary>
        /// Test the property 'ProductDataToGenerate'
        /// </summary>
        [Fact]
        public void ProductDataToGenerateTest()
        {
            // TODO unit test for the property 'ProductDataToGenerate'
        }
    }
}
