/*
 * aiproductdataenhancer/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using aiproductdataenhancer.Model;
using aiproductdataenhancer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace aiproductdataenhancer.Test.Model
{
    /// <summary>
    ///  Class for testing AiproductdataenhancerFillProductDataCheckRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AiproductdataenhancerFillProductDataCheckRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AiproductdataenhancerFillProductDataCheckRequest
        //private AiproductdataenhancerFillProductDataCheckRequest instance;

        public AiproductdataenhancerFillProductDataCheckRequestTests()
        {
            // TODO uncomment below to create an instance of AiproductdataenhancerFillProductDataCheckRequest
            //instance = new AiproductdataenhancerFillProductDataCheckRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AiproductdataenhancerFillProductDataCheckRequest
        /// </summary>
        [Fact]
        public void AiproductdataenhancerFillProductDataCheckRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" AiproductdataenhancerFillProductDataCheckRequest
            //Assert.IsType<AiproductdataenhancerFillProductDataCheckRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'JobId'
        /// </summary>
        [Fact]
        public void JobIdTest()
        {
            // TODO unit test for the property 'JobId'
        }
    }
}
