/*
 * aiproductdataenhancer/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using aiproductdataenhancer.Model;
using aiproductdataenhancer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace aiproductdataenhancer.Test.Model
{
    /// <summary>
    ///  Class for testing AiproductdataenhancerTone
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AiproductdataenhancerToneTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AiproductdataenhancerTone
        //private AiproductdataenhancerTone instance;

        public AiproductdataenhancerToneTests()
        {
            // TODO uncomment below to create an instance of AiproductdataenhancerTone
            //instance = new AiproductdataenhancerTone();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AiproductdataenhancerTone
        /// </summary>
        [Fact]
        public void AiproductdataenhancerToneInstanceTest()
        {
            // TODO uncomment below to test "IsType" AiproductdataenhancerTone
            //Assert.IsType<AiproductdataenhancerTone>(instance);
        }

        /// <summary>
        /// Test the property 'ToneType'
        /// </summary>
        [Fact]
        public void ToneTypeTest()
        {
            // TODO unit test for the property 'ToneType'
        }

        /// <summary>
        /// Test the property 'CustomTone'
        /// </summary>
        [Fact]
        public void CustomToneTest()
        {
            // TODO unit test for the property 'CustomTone'
        }
    }
}
