/*
 * aiproductdataenhancer/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using aiproductdataenhancer.Model;
using aiproductdataenhancer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace aiproductdataenhancer.Test.Model
{
    /// <summary>
    ///  Class for testing AiproductdataenhancerGenerateProductDataRequestProductInformation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AiproductdataenhancerGenerateProductDataRequestProductInformationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AiproductdataenhancerGenerateProductDataRequestProductInformation
        //private AiproductdataenhancerGenerateProductDataRequestProductInformation instance;

        public AiproductdataenhancerGenerateProductDataRequestProductInformationTests()
        {
            // TODO uncomment below to create an instance of AiproductdataenhancerGenerateProductDataRequestProductInformation
            //instance = new AiproductdataenhancerGenerateProductDataRequestProductInformation();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AiproductdataenhancerGenerateProductDataRequestProductInformation
        /// </summary>
        [Fact]
        public void AiproductdataenhancerGenerateProductDataRequestProductInformationInstanceTest()
        {
            // TODO uncomment below to test "IsType" AiproductdataenhancerGenerateProductDataRequestProductInformation
            //Assert.IsType<AiproductdataenhancerGenerateProductDataRequestProductInformation>(instance);
        }

        /// <summary>
        /// Test the property 'TextInfo'
        /// </summary>
        [Fact]
        public void TextInfoTest()
        {
            // TODO unit test for the property 'TextInfo'
        }

        /// <summary>
        /// Test the property 'ImageInfo'
        /// </summary>
        [Fact]
        public void ImageInfoTest()
        {
            // TODO unit test for the property 'ImageInfo'
        }
    }
}
