/*
 * aiproductdataenhancer/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using aiproductdataenhancer.Model;
using aiproductdataenhancer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace aiproductdataenhancer.Test.Model
{
    /// <summary>
    ///  Class for testing AiproductdataenhancerFillProductDataResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AiproductdataenhancerFillProductDataResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AiproductdataenhancerFillProductDataResponse
        //private AiproductdataenhancerFillProductDataResponse instance;

        public AiproductdataenhancerFillProductDataResponseTests()
        {
            // TODO uncomment below to create an instance of AiproductdataenhancerFillProductDataResponse
            //instance = new AiproductdataenhancerFillProductDataResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AiproductdataenhancerFillProductDataResponse
        /// </summary>
        [Fact]
        public void AiproductdataenhancerFillProductDataResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" AiproductdataenhancerFillProductDataResponse
            //Assert.IsType<AiproductdataenhancerFillProductDataResponse>(instance);
        }

        /// <summary>
        /// Test the property 'ProductDataFilled'
        /// </summary>
        [Fact]
        public void ProductDataFilledTest()
        {
            // TODO unit test for the property 'ProductDataFilled'
        }

        /// <summary>
        /// Test the property 'ConfidenceRate'
        /// </summary>
        [Fact]
        public void ConfidenceRateTest()
        {
            // TODO unit test for the property 'ConfidenceRate'
        }

        /// <summary>
        /// Test the property 'CompletionRate'
        /// </summary>
        [Fact]
        public void CompletionRateTest()
        {
            // TODO unit test for the property 'CompletionRate'
        }
    }
}
