/*
 * aiproductdataenhancer/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using aiproductdataenhancer.Model;
using aiproductdataenhancer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace aiproductdataenhancer.Test.Model
{
    /// <summary>
    ///  Class for testing GenerateProductDataRequestProductDataToGenerate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GenerateProductDataRequestProductDataToGenerateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GenerateProductDataRequestProductDataToGenerate
        //private GenerateProductDataRequestProductDataToGenerate instance;

        public GenerateProductDataRequestProductDataToGenerateTests()
        {
            // TODO uncomment below to create an instance of GenerateProductDataRequestProductDataToGenerate
            //instance = new GenerateProductDataRequestProductDataToGenerate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GenerateProductDataRequestProductDataToGenerate
        /// </summary>
        [Fact]
        public void GenerateProductDataRequestProductDataToGenerateInstanceTest()
        {
            // TODO uncomment below to test "IsType" GenerateProductDataRequestProductDataToGenerate
            //Assert.IsType<GenerateProductDataRequestProductDataToGenerate>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'ValueSet'
        /// </summary>
        [Fact]
        public void ValueSetTest()
        {
            // TODO unit test for the property 'ValueSet'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

        /// <summary>
        /// Test the property 'Tone'
        /// </summary>
        [Fact]
        public void ToneTest()
        {
            // TODO unit test for the property 'Tone'
        }
    }
}
