/*
 * aiproductdataenhancer/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using aiproductdataenhancer.Model;
using aiproductdataenhancer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace aiproductdataenhancer.Test.Model
{
    /// <summary>
    ///  Class for testing ProductInformationTextInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductInformationTextInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductInformationTextInfo
        //private ProductInformationTextInfo instance;

        public ProductInformationTextInfoTests()
        {
            // TODO uncomment below to create an instance of ProductInformationTextInfo
            //instance = new ProductInformationTextInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductInformationTextInfo
        /// </summary>
        [Fact]
        public void ProductInformationTextInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductInformationTextInfo
            //Assert.IsType<ProductInformationTextInfo>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
    }
}
