/*
 * aiproductdataenhancer/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using aiproductdataenhancer.Model;
using aiproductdataenhancer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace aiproductdataenhancer.Test.Model
{
    /// <summary>
    ///  Class for testing ProductInformationImageInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductInformationImageInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductInformationImageInfo
        //private ProductInformationImageInfo instance;

        public ProductInformationImageInfoTests()
        {
            // TODO uncomment below to create an instance of ProductInformationImageInfo
            //instance = new ProductInformationImageInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductInformationImageInfo
        /// </summary>
        [Fact]
        public void ProductInformationImageInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductInformationImageInfo
            //Assert.IsType<ProductInformationImageInfo>(instance);
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
    }
}
