/*
 * aiproductdataenhancer/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = aiproductdataenhancer.Client.OpenAPIDateConverter;

namespace aiproductdataenhancer.Model
{
    /// <summary>
    /// AiproductdataenhancerTranslateDataResponse
    /// </summary>
    [DataContract(Name = "aiproductdataenhancerTranslateDataResponse")]
    public partial class AiproductdataenhancerTranslateDataResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AiproductdataenhancerTranslateDataResponse" /> class.
        /// </summary>
        /// <param name="dataTranslated">dataTranslated.</param>
        /// <param name="confidenceRate">confidenceRate.</param>
        /// <param name="completionRate">completionRate.</param>
        public AiproductdataenhancerTranslateDataResponse(Dictionary<string, string> dataTranslated = default(Dictionary<string, string>), float confidenceRate = default(float), float completionRate = default(float))
        {
            this.DataTranslated = dataTranslated;
            this.ConfidenceRate = confidenceRate;
            this.CompletionRate = completionRate;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Gets or Sets DataTranslated
        /// </summary>
        [DataMember(Name = "dataTranslated", EmitDefaultValue = false)]
        public Dictionary<string, string> DataTranslated { get; set; }

        /// <summary>
        /// Gets or Sets ConfidenceRate
        /// </summary>
        [DataMember(Name = "confidenceRate", EmitDefaultValue = false)]
        public float ConfidenceRate { get; set; }

        /// <summary>
        /// Gets or Sets CompletionRate
        /// </summary>
        [DataMember(Name = "completionRate", EmitDefaultValue = false)]
        public float CompletionRate { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AiproductdataenhancerTranslateDataResponse {\n");
            sb.Append("  DataTranslated: ").Append(DataTranslated).Append("\n");
            sb.Append("  ConfidenceRate: ").Append(ConfidenceRate).Append("\n");
            sb.Append("  CompletionRate: ").Append(CompletionRate).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
