/*
 * aiproductdataenhancer/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = aiproductdataenhancer.Client.OpenAPIDateConverter;

namespace aiproductdataenhancer.Model
{
    /// <summary>
    /// AiproductdataenhancerFillProductDataCheckResponse
    /// </summary>
    [DataContract(Name = "aiproductdataenhancerFillProductDataCheckResponse")]
    public partial class AiproductdataenhancerFillProductDataCheckResponse : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public AiproductdataenhancerJobStatus? Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="AiproductdataenhancerFillProductDataCheckResponse" /> class.
        /// </summary>
        /// <param name="productDataFilled">productDataFilled.</param>
        /// <param name="confidenceRate">confidenceRate.</param>
        /// <param name="completionRate">completionRate.</param>
        /// <param name="status">status.</param>
        /// <param name="error">error.</param>
        public AiproductdataenhancerFillProductDataCheckResponse(Dictionary<string, string> productDataFilled = default(Dictionary<string, string>), float confidenceRate = default(float), float completionRate = default(float), AiproductdataenhancerJobStatus? status = default(AiproductdataenhancerJobStatus?), AiproductdataenhancerError error = default(AiproductdataenhancerError))
        {
            this.ProductDataFilled = productDataFilled;
            this.ConfidenceRate = confidenceRate;
            this.CompletionRate = completionRate;
            this.Status = status;
            this.Error = error;
        }

        /// <summary>
        /// Gets or Sets ProductDataFilled
        /// </summary>
        [DataMember(Name = "productDataFilled", EmitDefaultValue = false)]
        public Dictionary<string, string> ProductDataFilled { get; set; }

        /// <summary>
        /// Gets or Sets ConfidenceRate
        /// </summary>
        [DataMember(Name = "confidenceRate", EmitDefaultValue = false)]
        public float ConfidenceRate { get; set; }

        /// <summary>
        /// Gets or Sets CompletionRate
        /// </summary>
        [DataMember(Name = "completionRate", EmitDefaultValue = false)]
        public float CompletionRate { get; set; }

        /// <summary>
        /// Gets or Sets Error
        /// </summary>
        [DataMember(Name = "error", EmitDefaultValue = false)]
        public AiproductdataenhancerError Error { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AiproductdataenhancerFillProductDataCheckResponse {\n");
            sb.Append("  ProductDataFilled: ").Append(ProductDataFilled).Append("\n");
            sb.Append("  ConfidenceRate: ").Append(ConfidenceRate).Append("\n");
            sb.Append("  CompletionRate: ").Append(CompletionRate).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Error: ").Append(Error).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
