/*
 * aiproductdataenhancer/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = aiproductdataenhancer.Client.OpenAPIDateConverter;

namespace aiproductdataenhancer.Model
{
    /// <summary>
    /// AiproductdataenhancerGenerateProductDataResponse
    /// </summary>
    [DataContract(Name = "aiproductdataenhancerGenerateProductDataResponse")]
    public partial class AiproductdataenhancerGenerateProductDataResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AiproductdataenhancerGenerateProductDataResponse" /> class.
        /// </summary>
        /// <param name="productDataGenerated">productDataGenerated.</param>
        /// <param name="completionRate">completionRate.</param>
        public AiproductdataenhancerGenerateProductDataResponse(Dictionary<string, string> productDataGenerated = default(Dictionary<string, string>), float completionRate = default(float))
        {
            this.ProductDataGenerated = productDataGenerated;
            this.CompletionRate = completionRate;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Gets or Sets ProductDataGenerated
        /// </summary>
        [DataMember(Name = "productDataGenerated", EmitDefaultValue = false)]
        public Dictionary<string, string> ProductDataGenerated { get; set; }

        /// <summary>
        /// Gets or Sets CompletionRate
        /// </summary>
        [DataMember(Name = "completionRate", EmitDefaultValue = false)]
        public float CompletionRate { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AiproductdataenhancerGenerateProductDataResponse {\n");
            sb.Append("  ProductDataGenerated: ").Append(ProductDataGenerated).Append("\n");
            sb.Append("  CompletionRate: ").Append(CompletionRate).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
