/*
 * aiproductdataenhancer/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = aiproductdataenhancer.Client.OpenAPIDateConverter;

namespace aiproductdataenhancer.Model
{
    /// <summary>
    /// AiproductdataenhancerFillProductDataRequest
    /// </summary>
    [DataContract(Name = "aiproductdataenhancerFillProductDataRequest")]
    public partial class AiproductdataenhancerFillProductDataRequest : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets LanguageCode
        /// </summary>
        [DataMember(Name = "languageCode", EmitDefaultValue = false)]
        public AiproductdataenhancerLanguageCode? LanguageCode { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="AiproductdataenhancerFillProductDataRequest" /> class.
        /// </summary>
        /// <param name="tenantId">tenantId.</param>
        /// <param name="languageCode">languageCode.</param>
        /// <param name="productInformation">productInformation.</param>
        /// <param name="productDataToFill">productDataToFill.</param>
        /// <param name="domainsToInclude">domainsToInclude.</param>
        /// <param name="domainsToExclude">domainsToExclude.</param>
        public AiproductdataenhancerFillProductDataRequest(string tenantId = default(string), AiproductdataenhancerLanguageCode? languageCode = default(AiproductdataenhancerLanguageCode?), AiproductdataenhancerProductInformation productInformation = default(AiproductdataenhancerProductInformation), List<string> productDataToFill = default(List<string>), List<string> domainsToInclude = default(List<string>), List<string> domainsToExclude = default(List<string>))
        {
            this.TenantId = tenantId;
            this.LanguageCode = languageCode;
            this.ProductInformation = productInformation;
            this.ProductDataToFill = productDataToFill;
            this.DomainsToInclude = domainsToInclude;
            this.DomainsToExclude = domainsToExclude;
        }

        /// <summary>
        /// Gets or Sets TenantId
        /// </summary>
        [DataMember(Name = "tenantId", EmitDefaultValue = false)]
        public string TenantId { get; set; }

        /// <summary>
        /// Gets or Sets ProductInformation
        /// </summary>
        [DataMember(Name = "productInformation", EmitDefaultValue = false)]
        public AiproductdataenhancerProductInformation ProductInformation { get; set; }

        /// <summary>
        /// Gets or Sets ProductDataToFill
        /// </summary>
        [DataMember(Name = "productDataToFill", EmitDefaultValue = false)]
        public List<string> ProductDataToFill { get; set; }

        /// <summary>
        /// Gets or Sets DomainsToInclude
        /// </summary>
        [DataMember(Name = "domainsToInclude", EmitDefaultValue = false)]
        public List<string> DomainsToInclude { get; set; }

        /// <summary>
        /// Gets or Sets DomainsToExclude
        /// </summary>
        [DataMember(Name = "domainsToExclude", EmitDefaultValue = false)]
        public List<string> DomainsToExclude { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AiproductdataenhancerFillProductDataRequest {\n");
            sb.Append("  TenantId: ").Append(TenantId).Append("\n");
            sb.Append("  LanguageCode: ").Append(LanguageCode).Append("\n");
            sb.Append("  ProductInformation: ").Append(ProductInformation).Append("\n");
            sb.Append("  ProductDataToFill: ").Append(ProductDataToFill).Append("\n");
            sb.Append("  DomainsToInclude: ").Append(DomainsToInclude).Append("\n");
            sb.Append("  DomainsToExclude: ").Append(DomainsToExclude).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
